name: Python CI

on:
  push:
    branches: [ main, develop, 'sprint/*', 'feature/*' ]
    paths:
      - 'src/AIServices/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ main, develop, 'sprint/*' ]
    paths:
      - 'src/AIServices/**'
      - '.github/workflows/python-ci.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f src/AIServices/requirements.txt ]; then pip install -r src/AIServices/requirements.txt; fi
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src/AIServices --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 src/AIServices --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Test with pytest
        run: |
          # Use a basic test for now until module structure is fully set up
          python -m pytest src/AIServices/tests/test_basic.py -v

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: budgetronai-ai-services:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max